version: 2
updates:
  - package-ecosystem: docker
    directory: /services/Archival/Trickle.Archival.Api
    schedule:
      interval: daily
  - package-ecosystem: nuget
    directory: /services/Archival/Trickle.Archival.Api
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /services/Directory/Trickle.Directory.Api
    schedule:
      interval: daily
  - package-ecosystem: nuget
    directory: /services/Directory/Trickle.Directory.Api
    schedule:
      interval: daily
  - package-ecosystem: nuget
    directory: /services/Directory/Trickle.Directory.Infrastructure.Migrations.Tests
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /web
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: daily
